"""
FlightAware AeroAPI Data Ingest Module
=======================================

Fetches flight data from the FlightAware AeroAPI v4 REST endpoint and
converts the JSON responses into PySpark DataFrames for downstream
processing and persistence.

Generated by the aiSSEMBLE FlightAware REST API Ingest Backstage template.
"""

import logging
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import requests
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# FlightAware AeroAPI configuration
# ---------------------------------------------------------------------------
AEROAPI_BASE_URL = "${{ values.flightawareApiBaseUrl }}"
AEROAPI_ENDPOINT = "${{ values.flightawareApiEndpoint }}"
POLLING_INTERVAL_SECONDS = ${{ values.pollingIntervalSeconds }}

# ---------------------------------------------------------------------------
# PySpark schemas for FlightAware data
# ---------------------------------------------------------------------------
FLIGHT_SCHEMA = StructType(
    [
        StructField("fa_flight_id", StringType(), nullable=False),
        StructField("ident", StringType(), nullable=True),
        StructField("operator", StringType(), nullable=True),
        StructField("flight_number", StringType(), nullable=True),
        StructField("aircraft_type", StringType(), nullable=True),
        StructField("origin", StringType(), nullable=True),
        StructField("destination", StringType(), nullable=True),
        StructField("departure_time", TimestampType(), nullable=True),
        StructField("arrival_time", TimestampType(), nullable=True),
        StructField("status", StringType(), nullable=True),
        StructField("route_distance", DoubleType(), nullable=True),
        StructField("ingest_timestamp", TimestampType(), nullable=False),
    ]
)

POSITION_SCHEMA = StructType(
    [
        StructField("fa_flight_id", StringType(), nullable=False),
        StructField("latitude", DoubleType(), nullable=True),
        StructField("longitude", DoubleType(), nullable=True),
        StructField("altitude", IntegerType(), nullable=True),
        StructField("groundspeed", IntegerType(), nullable=True),
        StructField("heading", IntegerType(), nullable=True),
        StructField("timestamp", TimestampType(), nullable=True),
        StructField("ingest_timestamp", TimestampType(), nullable=False),
    ]
)


class FlightAwareClient:
    """Thin wrapper around the FlightAware AeroAPI v4."""

    def __init__(self, api_key: str, base_url: str = AEROAPI_BASE_URL) -> None:
        self._base_url = base_url.rstrip("/")
        self._session = requests.Session()
        self._session.headers.update(
            {
                "x-apikey": api_key,
                "Accept": "application/json; charset=UTF-8",
            }
        )

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    def fetch(
        self,
        endpoint: str,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Execute a GET request against the AeroAPI and return the JSON body.

        Raises
        ------
        requests.HTTPError
            If the API returns a non-2xx status code.
        """
        url = f"{self._base_url}{endpoint}"
        logger.info("GET %s  params=%s", url, params)
        response = self._session.get(url, params=params, timeout=30)
        response.raise_for_status()
        return response.json()

    def fetch_flights(
        self,
        endpoint: str = AEROAPI_ENDPOINT,
        params: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Fetch flight records, handling pagination transparently."""
        all_flights: List[Dict[str, Any]] = []
        next_cursor: Optional[str] = None

        while True:
            request_params = dict(params or {})
            if next_cursor:
                request_params["cursor"] = next_cursor

            data = self.fetch(endpoint, params=request_params)

            # AeroAPI wraps results under different keys depending on endpoint
            flights = (
                data.get("flights")
                or data.get("departures")
                or data.get("arrivals")
                or data.get("scheduled_departures")
                or data.get("scheduled_arrivals")
                or []
            )
            all_flights.extend(flights)

            # Pagination via the "links" object
            links = data.get("links")
            if links and links.get("next"):
                next_cursor = links["next"]
            else:
                break

        logger.info("Fetched %d flight records from %s", len(all_flights), endpoint)
        return all_flights


# ---------------------------------------------------------------------------
# Transformation helpers
# ---------------------------------------------------------------------------


def _safe_code(obj: Any, key: str = "code_icao") -> Optional[str]:
    """Safely extract a nested airport / operator code."""
    if isinstance(obj, dict):
        return obj.get(key) or obj.get("code_iata") or obj.get("code")
    return str(obj) if obj else None


def _parse_ts(value: Any) -> Optional[datetime]:
    """Parse an ISO-8601 timestamp string returned by AeroAPI."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def transform_flights(raw_flights: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Normalise raw AeroAPI JSON into flat rows matching ``FLIGHT_SCHEMA``."""
    now = datetime.now(timezone.utc)
    rows: List[Dict[str, Any]] = []
    for flight in raw_flights:
        rows.append(
            {
                "fa_flight_id": flight.get("fa_flight_id", ""),
                "ident": flight.get("ident"),
                "operator": _safe_code(flight.get("operator")),
                "flight_number": flight.get("flight_number"),
                "aircraft_type": _safe_code(flight.get("aircraft_type"), "type"),
                "origin": _safe_code(flight.get("origin")),
                "destination": _safe_code(flight.get("destination")),
                "departure_time": _parse_ts(
                    flight.get("actual_off")
                    or flight.get("estimated_off")
                    or flight.get("scheduled_off")
                ),
                "arrival_time": _parse_ts(
                    flight.get("actual_on")
                    or flight.get("estimated_on")
                    or flight.get("scheduled_on")
                ),
                "status": flight.get("status"),
                "route_distance": (
                    float(flight["route_distance"])
                    if flight.get("route_distance") is not None
                    else None
                ),
                "ingest_timestamp": now,
            }
        )
    return rows


def to_dataframe(
    spark: SparkSession,
    rows: List[Dict[str, Any]],
    schema: StructType = FLIGHT_SCHEMA,
) -> DataFrame:
    """Create a PySpark DataFrame from a list of row dicts."""
    return spark.createDataFrame(rows, schema=schema)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Entrypoint for scheduled / manual invocation
# ---------------------------------------------------------------------------


def run_ingest(
    spark: SparkSession,
    api_key: str,
    endpoint: str = AEROAPI_ENDPOINT,
    params: Optional[Dict[str, Any]] = None,
) -> DataFrame:
    """Execute a single ingest cycle: fetch -> transform -> DataFrame.

    Parameters
    ----------
    spark:
        Active ``SparkSession``.
    api_key:
        FlightAware AeroAPI key.
    endpoint:
        API path to call (default comes from template configuration).
    params:
        Optional query-string parameters forwarded to the API.

    Returns
    -------
    DataFrame
        A PySpark DataFrame conforming to ``FLIGHT_SCHEMA``.
    """
    client = FlightAwareClient(api_key=api_key)
    raw = client.fetch_flights(endpoint=endpoint, params=params)
    if not raw:
        logger.warning("No flights returned from %s", endpoint)
        return spark.createDataFrame([], schema=FLIGHT_SCHEMA)
    rows = transform_flights(raw)
    return to_dataframe(spark, rows)


def run_polling_loop(
    spark: SparkSession,
    api_key: str,
    endpoint: str = AEROAPI_ENDPOINT,
    params: Optional[Dict[str, Any]] = None,
    interval: int = POLLING_INTERVAL_SECONDS,
) -> None:
    """Continuously poll the FlightAware API at the configured interval.

    Each cycle writes the result as a new micro-batch.  Override or extend
    this function to plug in your own persistence logic.
    """
    logger.info(
        "Starting FlightAware polling loop  endpoint=%s  interval=%ds",
        endpoint,
        interval,
    )
    while True:
        try:
            df = run_ingest(spark, api_key, endpoint, params)
            logger.info("Ingest cycle complete  rows=%d", df.count())
        except requests.HTTPError:
            logger.exception("AeroAPI request failed; retrying next cycle")
        except Exception:
            logger.exception("Unexpected error during ingest cycle")

        time.sleep(interval)
